# Generated by Django 2.2.4 on 2019-09-09 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0007_auto_20190909_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desciption', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('5', 'High'), ('4', 'Medium/High'), ('3', 'Medium'), ('2', 'Medium/Low'), ('1', 'Low')], default='3', max_length=1)),
                ('status', models.CharField(choices=[('1', 'unassigned'), ('2', 'inprogress'), ('3', 'completed')], default='1', max_length=1)),
                ('repeat_task', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
    ]
