# Generated by Django 2.2.4 on 2019-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('board_picture', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color_scheme', models.TextField()),
                ('board_url', models.CharField(max_length=25)),
            ],
        ),
    ]
