# Generated by Django 2.2.4 on 2019-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='joining_code',
            field=models.CharField(default='QS255ZYR', max_length=10, unique=True),
        ),
    ]
