# Generated by Django 2.2.4 on 2019-09-09 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_auto_20190909_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='boardId',
            new_name='board_id',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='board',
            name='board_url',
            field=models.CharField(default='/t3r84gtr/', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='joining_code',
            field=models.CharField(default='t3r84gtr', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='BoardScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
