# Generated by Django 2.2.4 on 2019-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20190909_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_url',
            field=models.CharField(default='/gn5pnflw/', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='joining_code',
            field=models.CharField(default='gn5pnflw', max_length=10, unique=True),
        ),
    ]
