# Generated by Django 2.2.4 on 2019-09-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190909_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_url',
            field=models.CharField(default='/ro5np5co/', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='joining_code',
            field=models.CharField(default='ro5np5co', max_length=10, unique=True),
        ),
    ]
